app:
  name: "tgr-posts-api"
  port: "8080"

redis:
  host: ""
  pass: ""
  shortCache: 60
  longCache: 1800

mongo:
  connectionString: "mongodb://tgrapp:VGh1bmRlckAuNjIwMzAzVGh1bmRlckAuNjIwMzAz@10.148.0.4:1301"
  databaseName: "tgr_posts"
