app:
  name: "tgr-posts-api"
  port: "8080"

redis:
  host: ""
  pass: ""
  shortCache: 60
  longCache: 1800

mongo:
  connectionString: "mongodb://devtgradmin:dGh1bmRlcgo=@34.142.210.202:13001"
  databaseName: "tgr_posts"
